### ISSUE TITLE
What about CMake?

### ISSUE THREAD

**Issue by golxzn** [eyalz800/zpp_bits#103]
Would you like to add CMake support? It's not so hard for header-only library
You can use [this tool](https://github.com/friendlyanon/cmake-init) for making cmake project just in a few commands

**Comment by wxinix** [comment]
Cmake? co-ask.

**Comment by eyalz800** [comment]
Acknowledged the ask, I will free some time for this but I can’t promise it’s soon because I see this as a nice to have

**Comment by Traveller23** [comment]
It's a header only library, it doesn't need to "make" itself, so in my opinion cmake is not necessary.
This is how I reference it in my cmake project:
```
target_include_directories(my_test SYSTEM PRIVATE C:/Libraries/zpp_bits)
```
You could replace the path with variable `${ZPP_BITS_PATH}`, and then provide this variable to the cmake command, for example:
```
-DZPP_BITS_PATH="C:/Libraries/zpp_bits"
```

Anyway, you need a way to find the library, even with cmake.

**Comment by wxinix** [comment]
CMake is needed for the test cases

**Comment by Traveller23** [comment]
> CMake is needed for the test cases

Well, indeed it is.

**Comment by eyalz800** [comment]
But the test cases are not a dependency in your project

**Comment by wxinix** [comment]
not true if I want to learn the code and wish to contribute it, or 
deeply customize it.


------ Original Message ------
From "Eyal Z" ***@***.***>
To "eyalz800/zpp_bits" ***@***.***>
Cc "Wuping Xin" ***@***.***>; "Comment" 
***@***.***>
Date 2/15/2023 5:01:43 PM
Subject Re: [eyalz800/zpp_bits] What about CMake? (Issue #103)

**Comment by golxzn** [comment]
Well, CMake might be overkill for header only library, but as @wxinix said, it'll be great to cover code by tests.

> But the test cases are not a dependency in your project

But the case that I really want to achieve is cloning project during configuration step. I usually use [CPM](https://github.com/cpm-cmake/CPM.cmake) for managing project's dependencies. And it's pretty uncomfortable for me to load and insert some third_party stuff to the project. I enjoy to load dependencies into the build folder, which is ignored by git 🍰

**Comment by eyalz800** [comment]
Closed due to inactivity, as mentioned in above comments cmake transparently works with header only.
