### ISSUE TITLE
How to decouple input data and output data in RPC

### ISSUE THREAD

**Issue by blear-cadence** [eyalz800/zpp_bits#106]
I have tried to decouple input and output data when using RPC but I can't quite figure out if this is possible.  The motivation is: suppose I want to send a large set of data to a server, which will process the data and send back a relatively much smaller response.  Currently, it seems that I cannot create a separate output buffer to hold the response data from the RPC call in order to send a minimal amount of data back to the client, I am either forced to use the same size buffer or to reuse the input buffer as data.  Could you let me know if this is possible, and perhaps provide an example?  Here is a short example of what I'm trying to do:

```
// in_data is read from client socket
void process_client_request_and_send_to_client(
    std::vector< std::byte >& in_data )
{
    zpp::bits::in in{ in_data };
    // this fails to compile without initial sizing:
    std::vector< std::byte > out_data;
    // this works:
    // std::vector< std::byte > out_data( in_data.size(), std::byte( 'X' ) );
    zpp::bits::out out{ out_data };
    auto server = rpc::server( in, out );
    server.serve().or_throw();
    send_to_client( out_data );
}
```

**Comment by eyalz800** [comment]
Can you send me a fully compiling small code, or with few errors that you would like to fix in godbolt? 
It’s a bit hard to work with the sample you created I am not fully sure how things are going there

**Comment by blear-cadence** [comment]
Sorry about that, I didn't realize you had replied.  Here is a complete example.
[m_zpp_rpc_question.cc.txt](https://github.com/eyalz800/zpp_bits/files/11436751/m_zpp_rpc_question.cc.txt)

**Comment by eyalz800** [comment]
Check this: https://godbolt.org/z/GGKKvfrPr
I don't see why you say that the output vector without size does not compile.

In this example the returned data to the client is exactly what the response is, there is no request data together with the response.

Also, you can further save space required for the response by using varint for example like this:
https://godbolt.org/z/n3x5Ess9x

**Comment by eyalz800** [comment]
Try to reproduce the error with godbolt or attach the error in text

**Comment by blear-cadence** [comment]
I haven't used godbolt before, and I'll see what I can do, but in the meantime, here is the compile command that I used on Mac:

```
g++-12 -pipe -fdiagnostics-color=always -fPIC -pedantic -std=c++20 -I/Users/rael/dev/scratch -I/usr/local/include -O3 -Wall -Wextra -Werror -MMD -MF x64machgcco3/deps/.d.m_zpp_rpc_question -MP -MT x64machgcco3/objs/m_zpp_rpc_question.o -c m_zpp_rpc_question.cc -o x64machgcco3/objs/m_zpp_rpc_question.o
```

**Comment by eyalz800** [comment]
Here is the same compiler on godbolt with more or less the same flags
https://godbolt.org/z/sPjK3WETd - seems working. I suggest to disable this warning

**Comment by blear-cadence** [comment]
Yeah, I guess this is a Mac platform thing, very odd.  I will work around this on my Mac, I don't want you to have to pollute your code for what seems to be a very unreasonable failure with my system.

I am going to look again at your solution to my original question to make sure I understand it.
