### ISSUE TITLE
cannot decompose class type have non-static data members

### ISSUE THREAD

**Issue by AbanoubNassem** [eyalz800/zpp_bits#108]
given we have a base `msg` structure , how to make it work

```c++
struct msg {
    int type;
};

struct person : public msg {
    std::string name;
    int age{};
};

auto [data, in, out] = zpp::bits::data_in_out(zpp::bits::size2b{});

   out(person{1009, "Person1", 25});
    person p;
    in(p);
    
```

`error: cannot decompose class type 'person': both it and its base class 'msg' have non-static data members`

**Comment by eyalz800** [comment]
Check this issue resolution - https://github.com/eyalz800/zpp_bits/issues/90

There is no way to automatically get into the base class, I might introduce a better way to handle this, but currently see if the issue above helps you workaround classes with base classes.

**Comment by AbanoubNassem** [comment]
> Check this issue resolution - #90
> 
> There is no way to automatically get into the base class, I might introduce a better way to handle this, but currently see if the issue above helps you workaround classes with base classes.

from what I understand from that solution , is that every driveed class has to have extra boilerplate to work , any other solution that can be done once in the base class ?

**Comment by eyalz800** [comment]
I don’t believe there is a generic solution to this issue, because there is no way to enumerate the base classes of a class, but even if there was a way - there is still the issue that structured binding will not work if you have a class with a base class and both have data members - and because structured binding is what we use to serialize the data members - we have no option but to require this boilerplate anyway. Does that make sense?

**Comment by AbanoubNassem** [comment]
> I don’t believe there is a generic solution to this issue, because there is no way to enumerate the base classes of a class, but even if there was a way - there is still the issue that structured binding will not work if you have a class with a base class and both have data members - and because structured binding is what we use to serialize the data members - we have no option but to require this boilerplate anyway. Does that make sense?

yeah it makes sense now , thanks for the clarification .

the idea was to force adding a `Msg->type`, so the buffer structure will always be 2 bytes for size , followed by 2 bytes for type , so when I receive the `msg/packet`, I can easily know which `msg/packet` it is , so I can deserialize it to the correct structure based on the second two bytes of the buffer.

something like:

```c++
const uint16_t packetId = *reinterpret_cast<uint16_t*>(buffer + 2);
switch (packetId)
{
  case 1009:{
    //this is person packet/msg
    person p;
    in(p);
    break;
  }
}
```

hopefully I made it clear enough .

**Comment by eyalz800** [comment]
You are describing exactly what std::variant does for you without the switch case, go ahead and try it!

**Comment by eyalz800** [comment]
See this test code -
https://github.com/eyalz800/zpp_bits/blob/main/test/src/test_variant.cpp

**Comment by AbanoubNassem** [comment]
> See this test code - https://github.com/eyalz800/zpp_bits/blob/main/test/src/test_variant.cpp

sure , thanks for the reference.
