### ISSUE TITLE
Compilation fails with C++20 and C++23 with gcc 11.3

### ISSUE THREAD

**Issue by Himeshi** [eyalz800/zpp_bits#110]
Compiling `zpp_bits.h` into a static library using CMake produces the attached errors with both C++20 and C++23. GCC version is 11.3 and CMake version is 3.22.

[zpp_error.txt](https://github.com/eyalz800/zpp_bits/files/11338819/zpp_error.txt)

**Comment by Himeshi** [comment]
Standalone compilation works, so could be an issue with CMake.

**Comment by kkEngine** [comment]
Did you solve the issue?
I have the same issue with cmake and msvc compiler
If i create simple console app then it works fine
