### ISSUE TITLE
std::array treated as agregate

### ISSUE THREAD

**Issue by asolwa** [eyalz800/zpp_bits#111]
Hi,

I am trying to serialize POD structure that has std::array field, unfortunately it doesn't works.
At first glance, the library tries to unpack std::array, as it deals with aggregates.
Is it expected bahaviour?

Following link displays code example:
https://godbolt.org/z/6fGEda1ja

**Comment by eyalz800** [comment]
Nice catch, it isn’t detected in the tests because small arrays work, let me fix it

**Comment by eyalz800** [comment]
@asolwa check now please with the latest version.

**Comment by eyalz800** [comment]
This should be fixed already, please check and re-open if not.

**Comment by asolwa** [comment]
It still has problems if i pass some option.
Look at following example:
https://godbolt.org/z/536PWjKPY

**Comment by eyalz800** [comment]
Should be solved soon #114

**Comment by eyalz800** [comment]
Fixed in v4.4.16, thank you. Please re-open if this is still happening or other issues.
