### ISSUE TITLE
Please document serialisation format

### ISSUE THREAD

**Issue by burnpanck** [eyalz800/zpp_bits#125]
We are using an in-house serialisation library with many of the same goals as this library. Ours is based on the concepts of Apache Avro, which is also overhead-free given that the schema is supplied separately - in the case of C++ code, the source code can serve as the schema. For maintainability reasons however, we could consider to switch to yours instead at some point. But in order to evaluate if the format is indeed ticking our boxes, it would be great to have at least a high-level description of the serialisation format. From our perspective, there is no need for a full "spec", we're willing to read source-code if we need to know the details.

**Comment by eyalz800** [comment]
The format is basically serialize everything fixed size as plain bytes, in your platform endianness, and prepend 32 bit size to anything that is not fixed size such as vector, etc follows by serializing each element (both endianness and size type are customizable). Optional has a Boolean prepended to it to signal if it is empty, and variant has one byte zero based index prepended to it which is also customizable. Can’t think of anything else. There is a very short slide that describes the format in my cppcon video which you can search on YouTube, it doesn’t cover everything but it’s showing the idea.

**Comment by burnpanck** [comment]
Ok thanks, that already paints a picture. Maybe copy that paragraph to the README if you haven't already, in case others wonder? I'm somewhat old-fashioned, I don't watch YouTube videos in search for information (or maybe I'm just too impatient; I like to quickly pin-point the information, usually by a combination of search and scrolling).

It seems your format somewhat prioritises speed over space, which is of course a valid choice. In the very specific embedded environment we operate, every byte counts, so we will stick with Avro-style now, where integers are (usually) encoded variable-length.

**Comment by eyalz800** [comment]
Well this also supports variable length encoding, it’s just that by default it’s going to favor speed
