### ISSUE TITLE
Could zpp bits be used under c++17?

### ISSUE THREAD

**Issue by Yikai-Liao** [eyalz800/zpp_bits#143]
Recently, I'm choosing a suitable serialization library for my [project](https://github.com/Yikai-Liao/symusic). I find that zpp bits is not only super fast but also light weight and easy to use.

However, I noticed that there is some new features in c++20 used in this library like std::span. I also used std::span in my lib before, but it fails to be compiled in github actions in some platforms (I'm sorry that I don't remember well about the details). My solution is to use pointer instead of std::span.

So I wonder, if there is a solution to compile zpp bits under c++17? If not, I'll try to find out what really makes std::span compiled failed in github actions (Maybe install the latest version of compiler every time I run github actions?)

**Comment by eyalz800** [comment]
Can you show me this compilation failure? Never heard of this

**Comment by Yikai-Liao** [comment]
Sorry, I remember not being able to search for a solution last time (I didn't even know how to execute some bash commands in github action back then). But I just saw one on stackoverflow, and that issue is exactly what I met:

https://stackoverflow.com/questions/63606079/how-to-use-clang-10-or-gcc-10-when-building-via-github-actions

For short, I just need to add line to install gcc10 or newer version

**Comment by eyalz800** [comment]
Go for gcc-11 even because the library really needs as much C++20 as possible :) I believe my CI build is using gcc 11

**Comment by Yikai-Liao** [comment]
thanks a lot

**Comment by eyalz800** [comment]
Why not install gcc-11 as part of the ci script if your operating system does not come with gcc-11

**Comment by Yikai-Liao** [comment]
well， I get totally confused.

In that issue, it is said that c++20 is not currently supported. And numpy was working on making the new version available, whereas they had met some problems.

Well, its an old issue. Manylinux 2_28 now support, gcc12, although it is now set as default option.

I'll try it later on github actions.

BTW, I have tried zpp bits on my local env. And I am surprised that it is so easy to use, witch such a high performance.

**Comment by Yikai-Liao** [comment]
fine, compilations on all platforms are passed

https://github.com/Yikai-Liao/symusic/actions/runs/7131049519
