### ISSUE TITLE
Unclear Namespace Resolution Requirement When Using Library 

### ISSUE THREAD

**Issue by a-olguin** [eyalz800/zpp_bits#150]
First off, thank you for all the effort in making this library. It's pretty incredible. 

The issue:
When using the somewhat automagic `auto serialize(const your_type& in_ ) -> zpp::bits::members<n>;` syntax on nonaggregate types, the build will break if the `serialize` declaration and `your_type` declaration are not in the same namespace. This maybe be clear to other users, but it bit me hard during a project refactor. 

The build will fail as the number of members detected does not match the structured binding return, which is the signature of the serialize declaration not existing at all. A quick investigation with a colleague makes us think that the constexpr resolution in `number_of_members` is failing when the type is in another namespace. 
Specifically, we think it's walking down either the 6 or 8th case incorrectly since those attempt to serialize the type with 
`return decltype(serialize(std::declval<type>()))::value;` and 
`return decltype(serialize(std::declval<type>()))::members;` respectively. 

Note:
I'm only a somewhat intermediate C++ developer, and it wasn't clear to me that creating serialize methods needed to be inside the same namespace as the types themselves, and that this would only break upon inclusion of code that actually exercised the serialization of the type (allowing for bugs to survive through several compiles / commits). 

Here is a godbolt outlining what works, what doesn't, and a minimal representation of the original problem context from my project. 
https://godbolt.org/z/z6rqjzY47

**Comment by eyalz800** [comment]
Hi,

What you speak about is part of the language and is called argument dependent lookup. The same goes for cases where user defined types implement “swap” outside the class - it must be in the same namespace as the type in order for the argument dependent lookup to find the function.

Let me know if you need more information or have any question.
