### ISSUE TITLE
std::byte

### ISSUE THREAD

**Issue by Chrys4lisfag** [eyalz800/zpp_bits#151]
Honestly, std::byte is the most retarded thing I've met.
Firstly I thought it is cool to use proper type for bytes data and started to refactor my whole project to use std::byte but then I've faced a million compatibility issues with the third party libraries and standard types.
Blocked ctors, reinterpret_cast and memcpy everywhere.

Now I hate std::byte the most, is it possible to add some define to use std::uint8_t or smth similar, please?

**Comment by eyalz800** [comment]
Thanks for making me literally laugh about this because I kind of agree, but to be clear - which thing is not working for you with std::uint8_t

**Comment by Chrys4lisfag** [comment]
The most troublesome thing is initializing std::vector<std::uint8_t> as you can't use begin(), end() and it does not have data() + size ctor (even if it had, you would need to cast). And ofc you often don't want to just copy it, you want to use std::move.

std:;vector<std::uint8_t> is commonly used in 3 party libs, for example cryptopp (VectorSink), there is ArraySink (ptr+size) but in my case cryptopp handles resize itself when pass vector and for ArraySink you have to resize yourself (calc output block size etc).

Initalizing std::string (sometimes needed for legacy code, http libraries like cpr etc) with iterators. You can init with ptr + size but you have to cast ptr for this (if I recall correctly).

So when I use zpp, I have to create new vector + resize + memcpy when I could have just used std::move to target vector\ctor that accepts std::vector<std::uint8_t>

**Comment by eyalz800** [comment]
I think I know what you are trying to do but somehow I don't realize what is not working for you and what the issue is.
Suppose this code example - https://godbolt.org/z/exjTz4saK

**Comment by Chrys4lisfag** [comment]
That is my bad. I somehow missed that you can provide your own data source despite it is clearly demonstrated right in the readme🙃

**Comment by eyalz800** [comment]
No worries, glad it is working.
You can also pass a byte type to the various factory functions for example `data_in_out<std::uint8_t>()`
