### ISSUE TITLE
zpp::bits::number_of_members seems to miscount for aggregates that derive from an empty base type

### ISSUE THREAD

**Issue by DaedieGit** [eyalz800/zpp_bits#152]
I'm using Clang 17

to reproduce:

```
int main()
{
    struct Base{};
    struct Derived : Base
    {
        int value = 1;
    };

    static_assert(zpp::bits::number_of_members<Derived>() == 1);
}
```

**Comment by eyalz800** [comment]
Counting the members using the aggregate trick has its limitations and edge cases. Unfortunately this is one of the cases where we have to wait for P1061. In the meantime specify the number of members explicitly using one of the methods in the readme

**Comment by eyalz800** [comment]
Refer to the readme note about this flag, it relies on a behavior that was not entirely defined in the standard. Recently I believe it was clarified what is exactly the immediate context in sfinae errors and also clang fixed their code accordingly in clang 18
