### ISSUE TITLE
Warning, not all paths return a value

### ISSUE THREAD

**Issue by bjadamson** [eyalz800/zpp_bits#154]
Hello! I've been making great use of zpp_bits, thank you so much!

I ran into an issue today, I created the smallest program I could come up with to demonstrate the warning.

```C++
#include <variant>
#include <external/zpp/zpp_bits.h>

class TEST final
{
private:
  friend zpp::bits::access;
  TEST(void) noexcept = default;

public:
  TEST(int) noexcept {};
};

int
main(int, char **)
{
  std::vector<std::byte> bytes;
  zpp::bits::in in(bytes);

  std::variant<TEST, int> data{TEST{32}};
  (void)in(data);
  return EXIT_SUCCESS;
}

```

The compiler complains about not all control paths returning a value. I'm worried about this messing up my stack and corrupting my program. The [code](https://github.com/eyalz800/zpp_bits/blob/0fbd858f28a44be591ef70a7ae36106bd5bf5734/zpp_bits.h#L2973-L2997) in question.

```
warning C4715: '`zpp::bits::in<std::vector<enum std::byte,std::allocator<enum std::byte> > >::serialize_one<TEST,int,std::variant,enum std::byte &>'::`2'::<lambda_1>::operator()<zpp::bits::in<std::vector<enum std::byte,std::allocator<enum std::byte> > >,std::variant<TEST,int> >': not all control paths return a value
```

**Comment by eyalz800** [comment]
Thanks, checking

**Comment by eyalz800** [comment]
Can you check #155

**Comment by eyalz800** [comment]
This is supposed to be fixed now, thanks for reporting, and let me know if you have any issue

**Comment by bjadamson** [comment]
LGTM tyvm!
