### ISSUE TITLE
Can't serialize std::optional in a structure

### ISSUE THREAD

**Issue by dsiroky** [eyalz800/zpp_bits#156]
Hi!
Standalone std::optional<int> can be serialized but once it is in a structure then the structure can't be serialized.
Example: https://godbolt.org/z/1Go4Pqqa4
The error is most likely the same as in https://github.com/eyalz800/zpp_bits/issues/121.
How can I do it properly?
Thanks.

**Comment by eyalz800** [comment]
Please look in the readme that detecting number of members is not always possible - see https://godbolt.org/z/PPvqP8ozY, we need to wait for P1061 or reflection or some other workaround.

**Comment by dsiroky** [comment]
Thank you! Great library btw.

**Comment by eyalz800** [comment]
@dsiroky please see #190
