### ISSUE TITLE
Help with std::vector of a big object.

### ISSUE THREAD

**Issue by stayprivate** [eyalz800/zpp_bits#162]
Hello,

Code at: https://godbolt.org/z/3WW4fbs18

Ignore the ugliness of the structures.  Basically if serializing Board_t, it's all good, but if serializing std::vector<Board_t> it's as though zpp cannot find the custom serializer and thus default to internal automatic handling which fail because there are more than 50 variables, yet the custom serializer for Board_t only serialized one variable.

It will work if the custom serializer is put inside the Board_t struct  https://godbolt.org/z/4q9anToYo but that's not a viable solution for us.

Regards,

Mario

**Comment by eyalz800** [comment]
Try to put the serialize function in the same namespace as your type:
https://godbolt.org/z/onqPYTTT6

**Comment by stayprivate** [comment]
That did it thanks

**Comment by stayprivate** [comment]
That did it thanks
