### ISSUE TITLE
Warning when compiling with GCC 14

### ISSUE THREAD

**Issue by dns13** [eyalz800/zpp_bits#169]
Compilation with GCC 14.1.0 with `-std=c++23` is throwing the following warning:

> /xxx/zpp_bits.h: In static member function 'static constexpr decltype(auto) zpp::bits::bind_opaque<Function, Id, MaxSize>::call(auto:226&&, auto:227&&, auto:228&&)':
> /xxx/zpp_bits.h:3750:19: error: name-independent declarations only available with '-std=c++2c' or '-std=gnu++2c' [-Werror=c++26-extensions]
>  3750 |                 } _{in, in.remaining_data()};
>       |                   ^
> /xxx/zpp_bits.h:3774:19: error: name-independent declarations only available with '-std=c++2c' or '-std=gnu++2c' [-Werror=c++26-extensions]
>  3774 |                 } _{in, in.remaining_data()};
>       |                   ^

If I disable this warning, compilation works fine.

Probably the support for C++26s "Placeholder variables with no name" seems is the cause of this.

**Comment by eyalz800** [comment]
Correct, I’ll fix it

**Comment by dns13** [comment]
Thank you

**Comment by eyalz800** [comment]
Should be fixed with #170

**Comment by dns13** [comment]
Yes, working now. Thank you!
