### ISSUE TITLE
Can't de-serialize std::unique_ptr<T> with T being non default constructible

### ISSUE THREAD

**Issue by mzukovec** [eyalz800/zpp_bits#175]
Current state of the project does not allow the de-serialization of non trivially-constructible objects:

https://godbolt.org/z/ME5rvxEhe

**Comment by eyalz800** [comment]
That’s correct and by design, the typical workaround is a private constructor and friending the zpp::bits::access

**Comment by mzukovec** [comment]
What about unique_ptr with non-default deleter?

**Comment by eyalz800** [comment]
In that case it will require the library to also accept a way to allocate the object in a custom way and given the nature of the recursion that happens with all objects it’s not clear how to customize the allocation of one of the many potential nested objects - it definitely complicates. I hope in your case maybe we can discuss and find a workaround if this is needed

**Comment by mzukovec** [comment]
I'm currently solving it by extending the [static_assert](https://github.com/eyalz800/zpp_bits/blob/244f9c612f668bd466e2ee378a4998d3c577332c/zpp_bits.h#L1997) with `static_assert(!std::is_pointer_v<type> || access::has_explicit_serialize<type, in / basic_out>());` and using the explicit serialization method

**Comment by eyalz800** [comment]
Interesting approach, let me know if there is something to contribute back, I assume you are going with an external serialize function and some static assert in the library is conflicting
