### ISSUE TITLE
deserialization to std::bitset doesn't follow the endianness

### ISSUE THREAD

**Issue by YanzhaoW** [eyalz800/zpp_bits#176]
### Issue

The deserialization of std::bitset seems always to follow the little endian (the least significant digit comes first).

### Reproduce

Godbolt link: [https://godbolt.org/z/4MeaYcYTq](https://godbolt.org/z/4MeaYcYTq)

Code:

```c++
#include "zpp_bits.h"
#include <fmt/format.h>
#include <fmt/ranges.h>
#include <bitset>

void test()
{
    auto data = std::vector<uint8_t>{0x19, 0x5f, 0x1c, 0x7c, 0xb8, 0x7c, 0x43, 0x33};
    auto deserialize_to = zpp::bits::in{ data, zpp::bits::endian::network{} };

    auto my_struct = std::bitset<64>{};
    deserialize_to(my_struct).or_throw();
    fmt::print("deserialized bitset: {:x}\n", my_struct.to_ullong());

    deserialize_to.reset();
    auto my_struct2 = uint64_t{};
    deserialize_to(my_struct2).or_throw();
    fmt::print("deserialized int64: {:x}\n", my_struct2);
}

auto main() -> int
{
    test();
    return 0;
}
```
Output from console:
```text
deserialized bitset: 33437cb87c1c5f19
deserialized int64: 195f1c7cb87c4333
```

### Version info:

zpp_bits: latest version
compiler: gcc 14.2

**Comment by eyalz800** [comment]
Bitset underlying data is just an array of bytes, there should not be a byte order / endianness here, what am I missing?

**Comment by YanzhaoW** [comment]
Hi,

Thanks for the response. 

> Bitset underlying data is just an array of bytes, there should not be a byte order / endianness here

Did you actually "an array of bits" instead of "an array of bytes"? If we have an array of bytes, the byte order should matter.

But from the perspective of consistency, I think it would better if the deserialized `std::bit_set<64>::to_ullong()` has the same value as the `unsigned long long`.

**Comment by eyalz800** [comment]
No I literally meant that while being an array of bits, it stores the bits in some bytes (the underlying data) - which is why I referred to it an as array of bytes - and an array of bytes is a construct that does not have a byte order.

**Comment by YanzhaoW** [comment]
> because it is an array of bytes there is never a byte order, how could there be - maybe a bitset of 64 bits is actually meant to store 8 individual bytes and never represent a multibyte integer, maybe it represents four 2-byte integers - there is no telling

I think `std::bit_set` is normally treated as a consecutive bit sequence instead of array of integers. Therefore, in the case of `std::bit_set<64>`, it should be treated as a multibyte integer instead of an array. Also from the standard, `std::bit_set` only has interfaces like `to_ullong()` or `to_ulong()`, which could mean that `std::bit_set` represents a value instead of an array of values. So like other literal types (size of >1 byte), `std::bit_set` de/serialization should be depending on an endianness specified by the user. For now, the convention is quite unintuitive, from the byte arrays of `std::vector<char>{"0x10", "0x20", "0x30"}`, the deserialized bitset is actually `std::bitset<16>{"0x302010"}`.

> The same could be said about an std::array of bytes of course you can bitcast to a multibyte integer, but how could you assume the array of bytes is an integer of some size as opposed to just individual bytes

Sorry, I don't quite understand the ambiguity here. If I want to deserialize to a multibyte integer, I would do
```c++
uint64_t a{};
in(a); // With certain endian
```
If I want to deserialize to an array of bytes, I would do
```c++
auto byte_array = std::array<uint8_t, N>{}
in(byte_array); // No endianness
```
I don't quite know whether it's normal to represent a 4-byte integer using 4 chars instead of just `uint32_t`.

**Comment by eyalz800** [comment]
The same could be said about https://en.cppreference.com/w/cpp/utility/bitset/to_string

Would we want the string representation to change across the network when byte order is swapped?
