### ISSUE TITLE
Why isn't as_bytes serialization the "default" behavior?

### ISSUE THREAD

**Issue by quicknir** [eyalz800/zpp_bits#177]
Very cool looking library! One surprise was that I have to explicitly write

```
    constexpr static auto serialize(auto & archive, auto & self)
    {
        // Serialize as bytes, instead of serializing each
        // member separately. The overall result is the same, but this may be
        // faster sometimes.
        return archive(zpp::bits::as_bytes(self));
    }
```

Is there a reason why it's necessary to do this manually? Or maybe, even more fundamentally, what is this actually doing differently, and if it's always the same but possibly faster, surely it would just be the default?

**Comment by eyalz800** [comment]
For example padding, or stuff that has pointers inside, endianness, and more.
