### ISSUE TITLE
deserialize a std::string_view similar to std::span<const std::byte>

### ISSUE THREAD

**Issue by jkammerland** [eyalz800/zpp_bits#178]
Hello, maybe this is already possible and someone can point out how.

This is my opinion, I feel it would be natural to have a `std::string_view` (a view to a stringlike sequence of const bytes) behave like `std::span<const std::byte>` (a "view" of a sequence of const bytes). Right now it does not, from what I've tried and read up on.

To illustrate, without going into too much detail on my use case I provide this code:

```cpp
TEST_CASE("Tag string_view with cbor_tag") {
    auto [data, out]  = zpp::bits::data_out();
    auto [dataIn, in] = zpp::bits::data_in();

    // Data to transfer
    std::string_view s{"This is a string view"};

    // Encode data
    auto result = out(cbor::make_tag(1, s));
    CHECK(!failure(result));

    // Emulate data transfer
    dataIn = data;

    // Decode data (I would like to use string_view as type here, not std::span<const std::byte>)
    cbor::Tag<std::span<const std::byte>> s2;
    result = in(s2);
    CHECK(!failure(result));

    // Check data
    CHECK(1 == s2.first);
    CHECK(s == std::string_view(reinterpret_cast<const char *>(s2.second.data()), s2.second.size()));

    // Check data location is different (it was truly transferred)
    CHECK(s.data() != reinterpret_cast<const char *>(s2.second.data()));
}
```

I would like to avoid having to write extra layers and casting between them too much. If this is something that is possible to implement/change, I would be happy to help if needed.

**Comment by eyalz800** [comment]
I would really like to discourage deserializing into view types of const because this is not necessarily doing what you want - it just makes the view point to the data and is a bit dangerous - this is why it was restricted to span of const byte types only!

By the way - I would love to take a look at what you’re building there if it’s open source.

**Comment by jkammerland** [comment]
Hehe I can understand that reasoning. But in my specific case, I fully manage the lifetime of the buffer (and spans of it) where the data I would deserialize/interpret from reside. So the extra copy should not be necessary, but I'm definitely risking shooting myself in the foot. 

While I can't go into details on that because it's related to work, I can show something close enough, which I do plan making open source.

I just started and I am still exploring a bit, but I pushed it so you can see:
https://github.com/jkammerland/cbor_tags
see the "usage" section in the readme.

The examples in the "usage" section does not use zpp_bits, because that is still general cbor. I thought zpp_bits (or something like bitsery) could shine as an example for defining your own objects, aka tag (6) in cbor. The standard is very flexible here, you can literally claim any id for your object and define the binary structure as "how zpp_bits would serialize this c++ struct". This could very flexible if your type only travels within a limited system where you could share headers with struct definitions.

I plan to work on this when I have time and try to either use zpp_bits as an example for how you could make your own types. Maybe directly incorporate it with no/"a few" abstractions, to also handle cbor specifics.

Anyway, back to the std::string_view, the reason why I want const bytes, is because it's "necessary" to differentiate text strings and binary strings as a variant when dealing with the MAJOR types. Defaulting to no copy, and then building more safe abstractions on top if necessary. Don't know if it's a good idea, but I'm exploring it.

I tried to hack a bit to make it work, this is the diff on my fork (but not sure if good):
https://github.com/jkammerland/zpp_bits_fork_string_view/commit/b6e1263311c9290de4dc81d45dad8851030e2211

**Comment by eyalz800** [comment]
Thanks for the info there, I’m excited to see the progress you make. I think however for this feature request that it’s safer for the larger user base of the library to keep the behavior as it is rather than introducing implicit behaviors that could become footguns.

**Comment by jkammerland** [comment]
Sure @eyalz800 I understand. Thanks for taking a look. Please revisit my library in the future when I announce it on reddit or similar :)
