### ISSUE TITLE
Serialize std::list<T>

### ISSUE THREAD

**Issue by bjadamson** [eyalz800/zpp_bits#179]
Hi,

I don't know what you prefer but I found I can serialize `std::list<T>` (while continuing to support std::vector<T>) is by changing this line:
https://github.com/eyalz800/zpp_bits/blob/244f9c612f668bd466e2ee378a4998d3c577332c/zpp_bits.h#L2684

to use `container.front()` in place of container[0]

Do you have any thoughts if this is a good/bad idea? I see some other places in the library that container[0] is used as well.

**Comment by eyalz800** [comment]
True, it seems like a bug that was introduced, I’ll fix it and add tests for list

**Comment by eyalz800** [comment]
Should be fixed by https://github.com/eyalz800/zpp_bits/commit/129a9e3532e6999e488f34135d66f0b932170392
