### ISSUE TITLE
MSVC serialization issue

### ISSUE THREAD

**Issue by davidharabagiu** [eyalz800/zpp_bits#180]
Consider the following code:

```cpp
#include <string>
#include <cstddef>
#include <vector>
#include <iostream>
#include <zpp_bits.h>

struct A {
  std::string a;
};

std::vector<std::byte> serialize(const A& obj) {
  auto [bytes, serial_out] = zpp::bits::data_out();
  if (failure(serial_out(obj))) {
    std::cout << "serialize error\n";
    return {};
  }
  return bytes;
}

A deserialize(const std::vector<std::byte>>& b) {
  auto [bytes, serial_in] = zpp::bits::data_in();
  bytes = b;
  A obj;
  if (failure(serial_in(obj))) {
    std::cout << "deserialize error\n";
    return {};
  }
  return obj;
}

int main() {
  A obj {"test"};
  const auto bytes = serialize(obj);
  A obj2 = deserialize(bytes);
  std::cout << obj2.a << '\n';
  return 0;
}
```

With the MSVC that comes installed with Visual Studio 17.9.0, this code correctly prints "test". After updating to Visual Studio 17.11.5, running the code prints "deserialization error". I noticed that after the update, the serialized structure has a smaller size than before.

This doesn't happen with Clang or GCC.

**Comment by eyalz800** [comment]
Please check if this is the same issue https://github.com/eyalz800/zpp_bits/issues/164

I’m closing as duplicate for now, please re-open in case it’s a different issue.
