### ISSUE TITLE
Need help with custom serialization

### ISSUE THREAD

**Issue by arude** [eyalz800/zpp_bits#183]
I made a small example of a class I need to serialize. [https://godbolt.org/z/1r616sYz7](https://godbolt.org/z/1r616sYz7)
I'm not sure if I did this the thought of way or if there is a better more elaborate way. The class interface itself should not be changed. This simple test works as well, but as there is no example of a more complex custom serialization, I feel like I'm missing something.

How would you serialize this class with a standalone serialize overload?
```
class blubb final
{ // The class interface is as is and can't be touched!
  // This is a dummy for a more complex problem.
public:
  auto text1() const { return text1_; }
  auto text2() const { return text2_; }
  auto add(double d) { vec_.push_back(d); }
  auto get(std::size_t i) const { return vec_.at(i); }
  auto count() const { return vec_.size(); }
  auto text1(const std::string& val) { text1_ = val; }
  auto text2(const std::string& val) { text2_ = val; }
  auto operator==(const blubb&) const -> bool = default;

private:
  std::string text1_;
  std::vector<double> vec_;
  std::string text2_;
};
```

**Comment by eyalz800** [comment]
Please read the readme section that talks about "explicit serialization"

<img width="890" alt="image" src="https://github.com/user-attachments/assets/1459a04d-47e2-4985-8f56-87ac4d87b9e9">

**Comment by arude** [comment]
I did, multiple times. And as I wrote, "Can't touch the class". So this is not a solution! My problem can't be solved with this screenshot.

**Comment by eyalz800** [comment]
Keep reading that section it explains how to do it from outside the class

**Comment by arude** [comment]
I did, multiple times. This is not a solution since the members are private:
```
namespace my_namespace
{
struct person
{
    std::string name;
    int age{};
};

constexpr auto serialize(auto & archive, person & person)
{
    return archive(person.name, person.age);
}

constexpr auto serialize(auto & archive, const person & person)
{
    return archive(person.name, person.age);
}
} // namespace my_namespace
```
Further, the amount of serialization is dependent on a runtime function call. All of this is shown in my example.

**Comment by eyalz800** [comment]
I see that you have setter and getter for each member so you can via the external serialization function just serialize strings and explicitly call the getter and setter - you must first check if this is a load or save operation

**Comment by arude** [comment]
First, thank you for answering my questions.
I don't have access to vec_ directly. This is a very simplified example. Maybe only every nth member of something would needed to be serialized. Of course I could copy every thing into an easier struct, but this would then lead to an extra copy which should not be necessary. This is why I came up with this solution, where I wonder if this could be done easier:
```
static constexpr auto serialize(auto& archive, blubb& obj)
{
  using archive_type = std::remove_cvref_t<decltype(archive)>;
  using kind_type = decltype(archive_type::kind());

  if constexpr(archive_type::kind() == kind_type::in)
  { // Deserialization
    std::string text;
    if(const auto result = archive(text); failure(result))
    {
      return result;
    }
    obj.text1(text);

    std::uint32_t size;
    if(const auto result = archive(size); failure(result))
    {
      return result;
    }

    for(auto i = decltype(size){0}; i < size; ++i)
    {
      double d;
      if(const auto result = archive(d); failure(result))
      {
        return result;
      }
      obj.add(d);
    }

    const auto result = archive(text);
    if(failure(result))
    {
      return result;
    }
    obj.text2(text);
    
    return result;
  }
  else if constexpr(archive_type::kind() == kind_type::out)
  { // Serialize
    if constexpr(std::is_same_v<std::size_t, decltype(archive())>)
    { // Maybe size test run before serialization? Is this correct?
      auto result = archive(obj.text1());
      const std::uint32_t size = obj.count();
      result += archive(size);
      
      for(auto i = decltype(size){0}; i < size; ++i)
      {
        result += archive(obj.get(i));
      }
      
      return result + archive(obj.text2()); 
    }
    else
    { // Real serialization
      if(const auto result = archive(obj.text1()); failure(result))
      {
        return result;
      }

      const std::uint32_t size = obj.count();
      if(const auto result = archive(size); failure(result))
      {
        return result;
      }

      for(auto i = decltype(size){0}; i < size; ++i)
      {
        if(const auto result = archive(obj.get(i)); failure(result))
        {
          return result;
        }
      }
      
      return archive(obj.text2());
    }
  }
}
```

**Comment by eyalz800** [comment]
If you don’t have direct access you need to work around it by using the getters and setters and etc - it’s very manual process

**Comment by arude** [comment]
Yes, and I'm happy to do this manual process for some of my more complex needs. I only have one thing I don't fully understand. When compiling, I have to fulfil two cases for the kind::out. One for size_t and one for errc. Is the size_t for counting how many bytes the serialization would take? Is the check `if constexpr(std::is_same_v<std::size_t, decltype(archive())>)` good two distinguish those two cases?
I'm trying to replace my old self made serializer we're using in my company for over 10 years with this one. It is 100% binary compatible and has depending on use about the same performance. The major feature of course is PFR I want, but I some of the others mine lack are interesting as well.
