### ISSUE TITLE
Testing at runtime if archive is loading or saving

### ISSUE THREAD

**Issue by freemanix** [eyalz800/zpp_bits#68]
Hi,

Let's suppose I need to perform additional actions after the class members are loaded. How to determine if the `Archive` passed to `static void serialize(Archive & archive, Self & self)` member template method is loading or saving one? 

```cpp
template <typename Archive, typename Self>
static void serialize(Archive & archive, Self & self)
{
     archive(self.width, self.height);

     if (archive.is_loading())
         self.allocate(self.width, self.height);
}
```

**Comment by eyalz800** [comment]
Try this:
```cpp
if constexpr (Archive::kind() == zpp::bits::kind::in) {...} else {...}
```

**Comment by freemanix** [comment]
Do you have a different trick for your older zpp::serializer library? I am stuck on C++14 in some projects. Maybe SFINAE? How?

**Comment by eyalz800** [comment]
@freemanix with the old library you can wrap the check with a single SFINAE that checks whether it's a loading or saving archive and return a boolean (loading archives have a type named loading, saving have saving)

**Comment by eyalz800** [comment]
@freemanix anything else?

**Comment by freemanix** [comment]
Thank you for such fast response!
