### ISSUE TITLE
How to use RPC in real world?

### ISSUE THREAD

**Issue by aPSopt** [eyalz800/zpp_bits#69]
Hi!
I like your library!
But your RPC framework very strange. How to use it in real world? 
There are no any info how to use some transport, for example sockets.
Could you please add some examples?

**Comment by eyalz800** [comment]
The rpc is merely serializing a function call into data and serves a function call from a given data. You need to implement the transport in between, the library is not providing the transport

**Comment by aPSopt** [comment]
yes, I got you. 
But I don't have any idea how to attach own transport to your framework.
Could you show?

**Comment by eyalz800** [comment]
Choose whatever transport you want, then in the server you receive a message into a std::vector of bytes, you send this vector to the rpc using the example in the readme, and then you call serve on it, which will deserialize the call and invoke the function in the server.

For the client side this is similar except you are sending an empty vector to the rpc then you call it which will serialize the function call into the vector. Then you send the vector of bytes using your transport.

**Comment by eyalz800** [comment]
@aPSopt let me know if you need more info

**Comment by aPSopt** [comment]
Oh, ok, I found where I can get serialized buffer. Thx!

**Comment by eyalz800** [comment]
@darkomenz https://github.com/eyalz800/zpp_bits/blob/main/test/src/test_rpc.cpp

**Comment by darkomenz** [comment]
/*

Example real world application. For https://github.com/eyalz800/zpp_bits/issues/69

*/
#include <iostream>
#include <zpp_bits.h>
using namespace zpp::bits::literals;
/*

  This class is a shared object and is accessed from multiple threads / coroutines.
  Each function should be thread safe and implement locking.

*/
class Application : public std::enable_shared_from_this<Application>
{
  public:
    Application()
    {
      std::cout << "Application::Application" << std::endl;
    }
    ~Application()
    {
      std::cout << "Application::~Application" << std::endl;
    }
    std::string hello(std::string name)
    {
      std::cout << "Application::hello" << std::endl;
      return std::string("Hello ").append(name);
    }
};
/*

  This class implements socket communications. For this example data copying is used to simply the code;

*/
class Socket
{
  public:
    std::vector<std::byte> data;
};
/*

This class is for server rpc it is spawned inside multiple threads / coroutines (per connection) and accesses a shared object.

*/
class Server : public Socket
{
  public:
    Server(std::weak_ptr<Application> application) : server_rpc(zpp::bits::in<std::vector<std::byte>, zpp::bits::endian::network>(data, zpp::bits::endian::network{}), zpp::bits::out<std::vector<std::byte>, zpp::bits::endian::network>(data, zpp::bits::endian::network{}), application)
    {
      std::cout << "Server::Server" << std::endl;
    }
    ~Server()
    {
      std::cout << "Server::~Server" << std::endl;
    }
  public:
    zpp::bits::rpc<
      zpp::bits::bind<&Application::hello, "hello"_sha256_int>
    >::server<
      zpp::bits::in<std::vector<std::byte>, zpp::bits::endian::network>,
      zpp::bits::out<std::vector<std::byte>, zpp::bits::endian::network>,
      std::weak_ptr<Application>
    > server_rpc;
};
/*

This class is for client rpc it is spawned inside multiple threads / coroutines (per connection) and calls the server for responses.

*/
class Client : public Socket
{
  public:
    Client(Server& socket) : socket(socket), client_rpc(zpp::bits::in<std::vector<std::byte>, zpp::bits::endian::network>(data, zpp::bits::endian::network{}), zpp::bits::out<std::vector<std::byte>, zpp::bits::endian::network>(data, zpp::bits::endian::network{}))
    {
      std::cout << "Client::Client" << std::endl;
    }
    ~Client()
    {
      std::cout << "Client::~Client" << std::endl;
    }
    std::string hello(std::string name)
    {
      client_rpc.request<"hello"_sha256_int>(std::string("World")).or_throw();
      socket.data = data;
      socket.server_rpc.serve().or_throw();
      data = socket.data;
      return client_rpc.response<"hello"_sha256_int>().or_throw();
    }
  public:
    Server& socket;
    zpp::bits::rpc<
      zpp::bits::bind<&Application::hello, "hello"_sha256_int>
    >::client<
      zpp::bits::in<std::vector<std::byte>, zpp::bits::endian::network>,
      zpp::bits::out<std::vector<std::byte>, zpp::bits::endian::network>
    > client_rpc;
};
/*
  Example RPC Call between classes.
*/  
int main(int argc, char *argv[], char *envp[])
{
  Application application;
  Server server { application.weak_from_this() };
  Client client { server };
  try
  {
    std::cout << client.hello("World") << std::endl;
  }
  catch(...)
  {
    std::cout << "Caught Exception Aborted" << std::endl;
    return EXIT_FAILURE;
  }
  return EXIT_SUCCESS;
}

**Comment by darkomenz** [comment]
The example listed above is not currently possible in the framework because the RPC subsystem depends on r-values.
Can we add support for managed pointers?

**Comment by eyalz800** [comment]
@darkomenz can you paste the code with indentation?

**Comment by eyalz800** [comment]
Like here
```cpp
int main()
{
    return 0;
}
```

**Comment by eyalz800** [comment]
![Screen Shot 2022-04-19 at 9 50 58 AM](https://user-images.githubusercontent.com/29372486/164332949-0b57c812-afcf-4a30-97c8-588973630255.png)

**Comment by darkomenz** [comment]
@eyalz800 formatting is fixed now.

**Comment by eyalz800** [comment]
![Uploading Screenshot_20220421-010615.png…]()

**Comment by eyalz800** [comment]
@darkomenz I'm using phone at the moment can you point me to the line which has the error where it depends on rvalue

**Comment by darkomenz** [comment]
It would also be a good idea to add a optional message checksum such as crc32 for the on wire representation.
There have a been a few cases of large scale application faults due to hardware faults in the network card.

r-value required at zpp_bits.h: 3910

**Comment by eyalz800** [comment]
@darkomenz I think I see the issue.

All of the classes were designed with class template argument deduction and you were explicitly passing value type to the template which makes the constructor instantiate to require an rvalue.

If you used class template argument deduction it would have gone to the lvalue.

If you want to workaround you just make the rpc class with an lvalue reference to your input and output archives and it will make the constructor collapse to lvalue.

Does that make sense? @darkomenz

**Comment by eyalz800** [comment]
The workaround is like so:
```cpp
zpp::bits::rpc<
      zpp::bits::bind<&Application::hello, "hello"_sha256_int>
    >::client<
      zpp::bits::in<std::vector<std::byte>, zpp::bits::endian::network> &,
      zpp::bits::out<std::vector<std::byte>, zpp::bits::endian::network> &
    > client_rpc;
```

**Comment by darkomenz** [comment]
```c++

/*

Example real world application. For https://github.com/eyalz800/zpp_bits/issues/69

*/
#include <iostream>
#include <zpp_bits.h>
using namespace zpp::bits::literals;
/*

  This class is a shared object and is accessed from multiple threads / coroutines.
  Each function should be thread safe and implement locking.

*/
class Application : public std::enable_shared_from_this<Application>
{
  public:
    Application()
    {
      std::cout << "Application::Application" << std::endl;
    }
    ~Application()
    {
      std::cout << "Application::~Application" << std::endl;
    }
    std::string hello(std::string name)
    {
      std::cout << "Application::hello" << std::endl;
      return std::string("Hello ").append(name);
    }
};
/*

  This class implements socket communications. For this example data copying is used to simply the code;

*/
class Socket
{
  public:
    std::vector<std::byte> data;
};
/*

This class is for server rpc it is spawned inside multiple threads / coroutines (per connection) and accesses a shared object.

*/
class Server : public Socket
{
  public:
    Server(std::weak_ptr<Application> application) : in{ data, {} }, out{ data, {} }, server_rpc{ in, out, application }
    {
      std::cout << "Server::Server" << std::endl;
    }
    ~Server()
    {
      std::cout << "Server::~Server" << std::endl;
    }
  public:
    zpp::bits::in<std::vector<std::byte>, zpp::bits::endian::network> in;
    zpp::bits::out<std::vector<std::byte>, zpp::bits::endian::network> out;
    zpp::bits::rpc<
      zpp::bits::bind<&Application::hello, "hello"_sha256_int>
    >::server<
      zpp::bits::in<std::vector<std::byte>, zpp::bits::endian::network>&,
      zpp::bits::out<std::vector<std::byte>, zpp::bits::endian::network>&,
      std::weak_ptr<Application>&
    > server_rpc;
};
/*

This class is for client rpc it is spawned inside multiple threads / coroutines (per connection) and calls the server for responses.

*/
class Client : public Socket
{
  public:
    Client(Server& socket) : socket(socket), in{ data, {} }, out{ data, {} }, client_rpc{ in, out }
    {
      std::cout << "Client::Client" << std::endl;
    }
    ~Client()
    {
      std::cout << "Client::~Client" << std::endl;
    }
    std::string hello(std::string name)
    {
      client_rpc.request<"hello"_sha256_int>(std::string("World")).or_throw();
      socket.data = data;
      socket.server_rpc.serve().or_throw();
      data = socket.data;
      return client_rpc.response<"hello"_sha256_int>().or_throw();
    }
  public:
    Server& socket;
    zpp::bits::in<std::vector<std::byte>, zpp::bits::endian::network> in;
    zpp::bits::out<std::vector<std::byte>, zpp::bits::endian::network> out;
    zpp::bits::rpc<
      zpp::bits::bind<&Application::hello, "hello"_sha256_int>
    >::client<
      zpp::bits::in<std::vector<std::byte>, zpp::bits::endian::network>&,
      zpp::bits::out<std::vector<std::byte>, zpp::bits::endian::network>&
    > client_rpc;
};
/*
  Example RPC Call between classes.
*/  
int main(int argc, char *argv[], char *envp[])
{
  Application application;
  Server server { application.weak_from_this() };
  Client client { server };
  try
  {
    std::cout << client.hello("World") << std::endl;
  }
  catch(...)
  {
    std::cout << "Caught Exception Aborted" << std::endl;
    return EXIT_FAILURE;
  }
  return EXIT_SUCCESS;
}

```

ubuntu@ubuntu:~/C++/TestRPC$ make && ./TestRPC 
ccache g++ -std=c++2b -fcoroutines -march=native -I ../Dependencies/zpp_bits -Wall -Og -c Application.cpp -o Application.o
In file included from Application.cpp:7:
../Dependencies/zpp_bits/zpp_bits.h: In instantiation of ‘constexpr auto zpp::bits::apply(auto:184&&, auto:185&&, auto:186&&) requires (std::remove_cvref<decltype(zpp::bits::apply::archive)>::remove_cvref_t<decltype(zpp::bits::apply::archive)>::kind)() == zpp::bits::kind::in [with auto:184 = std::weak_ptr<Application>&; auto:185 = std::__cxx11::basic_string<char> (Application::*)(std::__cxx11::basic_string<char>); auto:186 = zpp::bits::in<std::vector<std::byte>, zpp::bits::options::endian::big>&]’:
../Dependencies/zpp_bits/zpp_bits.h:3626:25:   required from ‘static constexpr decltype(auto) zpp::bits::bind<Function, Id, MaxSize>::call(auto:189&&, auto:190&&) [with auto:189 = zpp::bits::in<std::vector<std::byte>, zpp::bits::options::endian::big>&; auto:190 = std::weak_ptr<Application>&; auto Function = &Application::hello; auto Id = 3125670444; auto MaxSize = -1]’
../Dependencies/zpp_bits/zpp_bits.h:3930:73:   required from ‘constexpr auto zpp::bits::rpc_impl<Bindings>::server<In, Out, Context>::call_binding(auto:200&) requires !(FirstBinding::opaque) [with FirstBinding = zpp::bits::bind<&Application::hello, 3125670444>; OtherBindings = {}; auto:200 = unsigned int; In = zpp::bits::in<std::vector<std::byte>, zpp::bits::options::endian::big>&; Out = zpp::bits::out<std::vector<std::byte>, zpp::bits::options::endian::big>&; Context = std::weak_ptr<Application>&; Bindings = {zpp::bits::bind<&Application::hello, 3125670444, -1>}]’
../Dependencies/zpp_bits/zpp_bits.h:4152:49:   required from ‘constexpr auto zpp::bits::rpc_impl<Bindings>::server<In, Out, Context>::serve(auto:202&&) [with auto:202 = unsigned int; In = zpp::bits::in<std::vector<std::byte>, zpp::bits::options::endian::big>&; Out = zpp::bits::out<std::vector<std::byte>, zpp::bits::options::endian::big>&; Context = std::weak_ptr<Application>&; Bindings = {zpp::bits::bind<&Application::hello, 3125670444, -1>}]’
../Dependencies/zpp_bits/zpp_bits.h:4162:38:   required from ‘constexpr auto zpp::bits::rpc_impl<Bindings>::server<In, Out, Context>::serve() [with In = zpp::bits::in<std::vector<std::byte>, zpp::bits::options::endian::big>&; Out = zpp::bits::out<std::vector<std::byte>, zpp::bits::options::endian::big>&; Context = std::weak_ptr<Application>&; Bindings = {zpp::bits::bind<&Application::hello, 3125670444, -1>}]’
Application.cpp:89:30:   required from here
../Dependencies/zpp_bits/zpp_bits.h:3598:63: error: pointer to member type ‘std::__cxx11::basic_string<char> (Application::)(std::__cxx11::basic_string<char>)’ incompatible with object type ‘std::weak_ptr<Application>’
 3598 |                     return (std::forward<decltype(self)>(self).*
      |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
 3599 |                             std::forward<decltype(function)>(function))(
      |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../Dependencies/zpp_bits/zpp_bits.h:3591:57: error: invalid use of void expression
 3591 |             return value_or_errc<return_type>(std::apply(
      |                                               ~~~~~~~~~~^
 3592 |                 [&](auto &&... arguments) -> decltype(auto) {
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 3593 |             // Ignore GCC issue.
      |             ~~~~~~~~~~~~~~~~~~~~                         
 3594 | #if defined __GNUC__ && !defined __clang__
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~               
 3595 | #pragma GCC diagnostic push
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~                              
 3596 | #pragma GCC diagnostic ignored "-Warray-bounds"
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~          
 3597 | #endif
      | ~~~~~~                                                   
 3598 |                     return (std::forward<decltype(self)>(self).*
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 3599 |                             std::forward<decltype(function)>(function))(
      |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 3600 |                         std::forward<decltype(arguments)>(arguments)...);
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 3601 | #if defined __GNUC__ && !defined __clang__
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~               
 3602 | #pragma GCC diagnostic pop
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~                               
 3603 | #endif
      | ~~~~~~                                                   
 3604 |                 },
      |                 ~~                                       
 3605 |                 std::move(parameters)));
      |                 ~~~~~~~~~~~~~~~~~~~~~~                   
make: *** [Makefile:15: Application.o] Error 1

**Comment by eyalz800** [comment]
Try to dereference the application instead of sending it as a weak pointer

**Comment by darkomenz** [comment]
Ok cool that fixed it but can we add support for the Smart Pointer types?

**Comment by eyalz800** [comment]
Depends on whether there is any added value, when I work with reference it automatically supports the smart pointer as well with a simple dereference

**Comment by darkomenz** [comment]
I believe in the std::shared_ptr case that would be fine but with std::weak_ptr when the object goes out of scope that would lead to crash correct?

**Comment by eyalz800** [comment]
@darkomenz you anyway avoid calling serve on the rpc if server is dead so I don't thing there is an issue with it

**Comment by darkomenz** [comment]
No worries I appreciate your help. Thank you for the assistance.
