### ISSUE TITLE
Serializing to/from file.

### ISSUE THREAD

**Issue by SlausB** [eyalz800/zpp_bits#70]
Hello!
Is there an established way of serializing directly to/from a file? Or one just would implement `data` with `push_back` and/or `append` methods and pass to `in`/`out`?
Thanks in advance!

**Comment by eyalz800** [comment]
I didn't implement writing / reading from a file, the you can read the file into your vector then deserialize or serialize to vector then write to the file.

If interested I also have a file library in my pinned repository since I prefer that interface over iostream.
