### ISSUE TITLE
What the format of serialized object?

### ISSUE THREAD

**Issue by qicosmos** [eyalz800/zpp_bits#71]
Could you provide a doc describe the format of a serialized object, how to arrange the members in memory?
Another question: https://github.com/eyalz800/zpp_bits/blob/main/zpp_bits.h#L1860
What the algorithm of enlarge_for, no UT for it.

**Comment by eyalz800** [comment]
About the format - its basically byte by byte copy depending on your byte order. Padding is skipped. In all other cases I think I was careful to explain what the overhead is such as -
For containers and strings they are length prefixes, variant is index prefixed, etc.

**Comment by qicosmos** [comment]
Thanks for your reply.
I did a test:
```c++
struct dummy {
  std::string str;
};

std::string str = "it is a test"; //length:12
out(dummy{str}).or_throw();
```
there will be three times m_data.resize:

1. resize(6) and copy length of the str;
2. resize(27) and copy the str data;
3. resize the real size 4+12;

So i think the enlarge_for is not efficient.

I think it can be improved resize once at the beginning, resize(4+12), what do you think?

**Comment by qicosmos** [comment]
A possible idea: for_each all members, get the total length firstly, and resize total only one time, avoid resize many times.

**Comment by eyalz800** [comment]
@qicosmos if you want to have less resizes you should make your initial vector large enough and then the enlarge for will do nothing because the vector is large enough

**Comment by qicosmos** [comment]
Yes, options::resize can init with large size.
I think the m_data can be init with a constexpr size: sizeof(some_object), if the real size is less of equal the init size, no resize any more, otherwise resize the data as before.

**Comment by eyalz800** [comment]
I think that for the case you proveed with std::string it will not be sufficient because sizeof(string) could be smaller than the string data yielding the unwanted resize.

**Comment by qicosmos** [comment]
I'm not sure if it would be slower than current, maybe i will do a benchmark to test get total size of serializing object firstly.

**Comment by qicosmos** [comment]
I set the m_data large enough, the result shows no better benchmark result, maybe it's not the hotspot.

**Comment by eyalz800** [comment]
@qicosmos you can try a span it's very similar in performance to a vector even though it doesn't grow

**Comment by qicosmos** [comment]
I don't think it will help a lot.

**Comment by eyalz800** [comment]
I see, let me know if you need anything more while you explore the library

**Comment by qicosmos** [comment]
Thank you.
