### ISSUE TITLE
Raspberry Pi - GCC Complication Error

### ISSUE THREAD

**Issue by darkomenz** [eyalz800/zpp_bits#73]
pi@raspberrypi:~/C++/RaftConsensusProtocol $ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/10/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 10.2.1-6' --with-bugurl=file:///usr/share/doc/gcc-10/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-10 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-mutex
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.1 20210110 (Debian 10.2.1-6) 

CC = ccache g++
CFLAGS = -std=c++2a -fcoroutines -Wall -march=native -O3 -I../Dependencies/zpp_bits
LDFLAGS = -pthread -lssl -lcrypto -ldl -l:libboost_json.a -l:libboost_url.a
EXECUTABLE = RaftConsensusProtocol
OBJECTS = Application.o

all: $(EXECUTABLE)
clean:
	rm -rf $(EXECUTABLE) $(OBJECTS)
$(EXECUTABLE): $(OBJECTS)
	$(CC) $(OBJECTS) -o $(EXECUTABLE) $(LDFLAGS)
%.o: %.cpp
	$(CC) $(CFLAGS) -c $< -o $@

pi@raspberrypi:~/C++/RaftConsensusProtocol $ make clean && time make && ./RaftConsensusProtocol
rm -rf RaftConsensusProtocol Application.o
ccache g++ -std=gnu++2a -fcoroutines -Wall -march=native -O3 -I../Dependencies/zpp_bits -c Application.cpp -o Application.o
In file included from Networking/PCH.hpp:34,
                 from Application.cpp:14:
../Dependencies/zpp_bits/zpp_bits.h: In function ‘constexpr ToType zpp::bits::std::bit_cast(const FromType&)’:
../Dependencies/zpp_bits/zpp_bits.h:80:37: error: expected primary-expression before ‘,’ token
   80 |     return __builtin_bit_cast(ToType, from);
      |                                     ^
../Dependencies/zpp_bits/zpp_bits.h: In instantiation of ‘constexpr ToType zpp::bits::std::bit_cast(const FromType&) [with ToType = std::array<unsigned char, 4>; FromType = zpp::bits::numbers::big_endian<unsigned int>; <template-parameter-1-3> = void]’:
../Dependencies/zpp_bits/zpp_bits.h:5141:80:   required from ‘constexpr auto zpp::bits::numbers::operator+(zpp::bits::numbers::big_endian<unsigned int>, zpp::bits::numbers::big_endian<unsigned int>)’
../Dependencies/zpp_bits/zpp_bits.h:5164:25:   required from ‘constexpr auto& zpp::bits::numbers::big_endian<Type>::operator+=(zpp::bits::numbers::big_endian<Type>) [with Type = unsigned int]’
../Dependencies/zpp_bits/zpp_bits.h:5266:15:   required from here
../Dependencies/zpp_bits/zpp_bits.h:80:30: error: ‘__builtin_bit_cast’ was not declared in this scope; did you mean ‘__builtin_strcat’?
   80 |     return __builtin_bit_cast(ToType, from);
      |            ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
      |            __builtin_strcat
../Dependencies/zpp_bits/zpp_bits.h: In instantiation of ‘constexpr ToType zpp::bits::std::bit_cast(const FromType&) [with ToType = zpp::bits::numbers::big_endian<unsigned int>; FromType = std::array<unsigned char, 4>; <template-parameter-1-3> = void]’:
../Dependencies/zpp_bits/zpp_bits.h:5154:41:   required from ‘constexpr auto zpp::bits::numbers::operator+(zpp::bits::numbers::big_endian<unsigned int>, zpp::bits::numbers::big_endian<unsigned int>)’
../Dependencies/zpp_bits/zpp_bits.h:5164:25:   required from ‘constexpr auto& zpp::bits::numbers::big_endian<Type>::operator+=(zpp::bits::numbers::big_endian<Type>) [with Type = unsigned int]’
../Dependencies/zpp_bits/zpp_bits.h:5266:15:   required from here
../Dependencies/zpp_bits/zpp_bits.h:80:30: error: ‘__builtin_bit_cast’ was not declared in this scope; did you mean ‘__builtin_strcat’?
   80 |     return __builtin_bit_cast(ToType, from);
      |            ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
      |            __builtin_strcat
../Dependencies/zpp_bits/zpp_bits.h: In instantiation of ‘constexpr ToType zpp::bits::std::bit_cast(const FromType&) [with ToType = zpp::bits::numbers::big_endian<unsigned int>; FromType = std::array<std::byte, 4>; <template-parameter-1-3> = void]’:
../Dependencies/zpp_bits/zpp_bits.h:1217:64:   required from ‘static constexpr auto zpp::bits::access::endian_independent_byte_serializable() [with Type = zpp::bits::numbers::big_endian<unsigned int>]’
../Dependencies/zpp_bits/zpp_bits.h:820:55:   required from ‘constexpr zpp::bits::errc zpp::bits::basic_out<ByteView, Options>::serialize_one(auto:133&&) [with auto:133 = zpp::bits::numbers::big_endian<unsigned int>&; ByteView = std::array<std::byte, 20>; Options = {}]’
../Dependencies/zpp_bits/zpp_bits.h:1902:40:   required from ‘constexpr zpp::bits::errc zpp::bits::basic_out<ByteView, Options>::serialize_many(auto:131&&, auto:132&& ...) [with auto:131 = zpp::bits::numbers::big_endian<unsigned int>&; auto:132 = {zpp::bits::numbers::big_endian<unsigned int>&, zpp::bits::numbers::big_endian<unsigned int>&, zpp::bits::numbers::big_endian<unsigned int>&, zpp::bits::numbers::big_endian<unsigned int>&}; ByteView = std::array<std::byte, 20>; Options = {}]’
../Dependencies/zpp_bits/zpp_bits.h:2319:34:   required from ‘constexpr auto zpp::bits::out<ByteView, Options>::operator()(auto:146&& ...) [with auto:146 = {zpp::bits::numbers::big_endian<unsigned int>&, zpp::bits::numbers::big_endian<unsigned int>&, zpp::bits::numbers::big_endian<unsigned int>&, zpp::bits::numbers::big_endian<unsigned int>&, zpp::bits::numbers::big_endian<unsigned int>&}; ByteView = std::array<std::byte, 20>; Options = {}]’
../Dependencies/zpp_bits/zpp_bits.h:5274:40:   required from here
../Dependencies/zpp_bits/zpp_bits.h:80:30: error: ‘__builtin_bit_cast’ was not declared in this scope; did you mean ‘__builtin_strcat’?
   80 |     return __builtin_bit_cast(ToType, from);
      |            ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
      |            __builtin_strcat
../Dependencies/zpp_bits/zpp_bits.h: In instantiation of ‘constexpr ToType zpp::bits::std::bit_cast(const FromType&) [with ToType = std::array<std::byte, 4>; FromType = unsigned int; <template-parameter-1-3> = void]’:
../Dependencies/zpp_bits/zpp_bits.h:1959:46:   required from ‘constexpr zpp::bits::errc zpp::bits::basic_out<ByteView, Options>::serialize_one(auto:133&&) [with auto:133 = unsigned int&; ByteView = std::array<std::byte, 20>; Options = {}]’
../Dependencies/zpp_bits/zpp_bits.h:1902:40:   required from ‘constexpr zpp::bits::errc zpp::bits::basic_out<ByteView, Options>::serialize_many(auto:131&&, auto:132&& ...) [with auto:131 = unsigned int&; auto:132 = {}; ByteView = std::array<std::byte, 20>; Options = {}]’
../Dependencies/zpp_bits/zpp_bits.h:2047:51:   required from ‘zpp::bits::basic_out<ByteView, Options>::serialize_one<zpp::bits::numbers::big_endian<unsigned int>&>::<lambda(auto:144&& ...)> [with auto:144 = {unsigned int&}]’
../Dependencies/zpp_bits/zpp_bits.h:215:127:   required from ‘static constexpr decltype(auto) zpp::bits::access::visit_members(auto:50&&, auto:51&&) requires 0 <= number_of_members<decltype(zpp::bits::access::visit_members::object)>() && number_of_members<decltype(zpp::bits::access::visit_members::object)>() <= zpp::bits::access::max_visit_members [with auto:50 = zpp::bits::numbers::big_endian<unsigned int>&; auto:51 = zpp::bits::basic_out<ByteView, Options>::serialize_one<zpp::bits::numbers::big_endian<unsigned int>&>::<lambda(auto:144&& ...)>&]’
../Dependencies/zpp_bits/zpp_bits.h:1349:33:   required from ‘constexpr decltype(auto) zpp::bits::visit_members(auto:118&&, auto:119&&) [with auto:118 = zpp::bits::numbers::big_endian<unsigned int>&; auto:119 = zpp::bits::basic_out<ByteView, Options>::serialize_one<zpp::bits::numbers::big_endian<unsigned int>&>::<lambda(auto:144&& ...)>]’
../Dependencies/zpp_bits/zpp_bits.h:2044:33:   required from ‘constexpr zpp::bits::errc zpp::bits::basic_out<ByteView, Options>::serialize_one(auto:133&&) [with auto:133 = zpp::bits::numbers::big_endian<unsigned int>&; ByteView = std::array<std::byte, 20>; Options = {}]’
../Dependencies/zpp_bits/zpp_bits.h:1902:40:   required from ‘constexpr zpp::bits::errc zpp::bits::basic_out<ByteView, Options>::serialize_many(auto:131&&, auto:132&& ...) [with auto:131 = zpp::bits::numbers::big_endian<unsigned int>&; auto:132 = {zpp::bits::numbers::big_endian<unsigned int>&, zpp::bits::numbers::big_endian<unsigned int>&, zpp::bits::numbers::big_endian<unsigned int>&, zpp::bits::numbers::big_endian<unsigned int>&}; ByteView = std::array<std::byte, 20>; Options = {}]’
../Dependencies/zpp_bits/zpp_bits.h:2319:34:   required from ‘constexpr auto zpp::bits::out<ByteView, Options>::operator()(auto:146&& ...) [with auto:146 = {zpp::bits::numbers::big_endian<unsigned int>&, zpp::bits::numbers::big_endian<unsigned int>&, zpp::bits::numbers::big_endian<unsigned int>&, zpp::bits::numbers::big_endian<unsigned int>&, zpp::bits::numbers::big_endian<unsigned int>&}; ByteView = std::array<std::byte, 20>; Options = {}]’
../Dependencies/zpp_bits/zpp_bits.h:5274:40:   required from here
../Dependencies/zpp_bits/zpp_bits.h:80:30: error: ‘__builtin_bit_cast’ was not declared in this scope; did you mean ‘__builtin_strcat’?
   80 |     return __builtin_bit_cast(ToType, from);
      |            ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
      |            __builtin_strcat

https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html

Built-in Function: type __builtin_bit_cast (type, arg)
The __builtin_bit_cast function is available only in C++. The built-in is intended to be used by implementations of the std::bit_cast C++ template function. Programs should make use of the latter function rather than invoking the built-in directly.

This built-in function allows reinterpreting the bits of the arg argument as if it had type type. type and the type of the arg argument need to be trivially copyable types with the same size. When manifestly constant-evaluated, it performs extra diagnostics required for std::bit_cast and returns a constant expression if arg is a constant expression. For more details refer to the latest revision of the C++ standard.

**Comment by darkomenz** [comment]
I found the github workflows and it looks like I need gcc 11 or higher.
I found a new operating system image from https://cdimage.ubuntu.com/releases/22.04/beta/ and installed it on the pi and it compiles.

**Comment by eyalz800** [comment]
Great
