### ISSUE TITLE
Compiling with MSVC results in a "fatal error C1001: Internal compiler error"

### ISSUE THREAD

**Issue by aymanalqadhi** [eyalz800/zpp_bits#77]
When I compile the following code with Visual Studio 2022 Preview 5, I get an error

```cpp
template <typename Container>
  static auto parse(Container&& buf, dos_header& header) -> std::error_code {
    if (buf.size() < size) {
      return make_error_code(deep::parser::parse_error::too_small_buffer);
    }

    auto in = zpp::bits::input(buf); // this is the line that causes the error (probably)
    in(header);

    if (header.e_magic != magic) {
      return deep::parser::make_error_code(
          deep::parser::parse_error::invalid_magic_number);
    }

    return {};
  }
```

The error I get:
`
 fatal error C1001: Internal compiler error. 
    (compiler file 'D:\a\_work\1\s\src\vctools\Compiler\CxxFE\sl\p1\c\module\parse-tree-resolve.cpp', line 736)
     To work around this problem, try simplifying or changing the program near the locations listed above.
`

**Comment by aymanalqadhi** [comment]
Full class code:

```cpp

struct dos_header {
  static constexpr std::uint16_t size  = 64UL;
  static constexpr std::uint16_t magic = 0x5A4DU;

  std::uint16_t e_magic;
  std::uint16_t e_cblp;
  std::uint16_t e_cp;
  std::uint16_t e_crlc;
  std::uint16_t e_cparhdr;
  std::uint16_t e_minalloc;
  std::uint16_t e_maxalloc;
  std::uint16_t e_ss;
  std::uint16_t e_sp;
  std::uint16_t e_csum;
  std::uint16_t e_ip;
  std::uint16_t e_cs;
  std::uint16_t e_lfarlc;
  std::uint16_t e_ovno;
  std::uint16_t e_res[4];
  std::uint16_t e_oemid;
  std::uint16_t e_oeminfo;
  std::uint16_t e_res2[10];
  std::uint32_t e_lfanew;

  static auto parse(std::vector<std::uint8_t>& buf, dos_header& header) -> std::error_code {
    if (buf.size() < size) {
      return make_error_code(deep::parser::parse_error::too_small_buffer);
    }

    auto in = zpp::bits::input(buf);
    in(header);

    if (header.e_magic != magic) {
      return deep::parser::make_error_code(
          deep::parser::parse_error::invalid_magic_number);
    }

    return {};
  }
};

static_assert(sizeof(dos_header) == dos_header::size);
```

**Comment by eyalz800** [comment]
Which msvc version are you using?

**Comment by aymanalqadhi** [comment]
This is from the output of cmake's configuration:

`1> [CMake] -- The C compiler identification is MSVC 19.33.31629.0`

**Comment by eyalz800** [comment]
Can you try just for sanity to turn the two regular arrays in the struct to std::array?

**Comment by eyalz800** [comment]
Another possible experiment is to add to the class `using serialize = zpp::bits::members<19>;`

**Comment by eyalz800** [comment]
Link to my experiment:
https://godbolt.org/z/sYG6TPYq6

**Comment by aymanalqadhi** [comment]
Neither has worked. My code now looks as the following after applying your fixes:

```cpp
struct dos_header {
  using serialize = zpp::bits::members<19>;

  static constexpr std::uint16_t size  = 64UL;
  static constexpr std::uint16_t magic = 0x5A4DU;

  std::uint16_t e_magic;
  std::uint16_t e_cblp;
  std::uint16_t e_cp;
  std::uint16_t e_crlc;
  std::uint16_t e_cparhdr;
  std::uint16_t e_minalloc;
  std::uint16_t e_maxalloc;
  std::uint16_t e_ss;
  std::uint16_t e_sp;
  std::uint16_t e_csum;
  std::uint16_t e_ip;
  std::uint16_t e_cs;
  std::uint16_t e_lfarlc;
  std::uint16_t e_ovno;
  std::array<uint16_t, 4> e_res;
  std::uint16_t e_oemid;
  std::uint16_t e_oeminfo;
  std::array<std::uint16_t, 10> e_res2;
  std::uint32_t e_lfanew;

  template <typename Container>
  static auto parse(Container&& buf, dos_header& header) -> std::error_code {
    if (buf.size() < size) {
      return make_error_code(deep::parser::parse_error::too_small_buffer);
    }

    auto in = zpp::bits::input(buf);
    in(header);

    if (header.e_magic != magic) {
      return deep::parser::make_error_code(
          deep::parser::parse_error::invalid_magic_number);
    }

    return {};
  }
};
```

**Comment by aymanalqadhi** [comment]
The problem is fixed though when I remove the template, and use std::vector directly (either as an lvalue or an rvalue) as the function's parameter. Is this by design, or am I doing something wrong?

**Comment by aymanalqadhi** [comment]
It also worked with C++20's `std::span` (which gives the ability to use most contiguous containers). However, it still does not work with templates

**Comment by aymanalqadhi** [comment]
The following code compiles successfully:

```cpp
struct dos_header {
  using serialize = zpp::bits::members<19>;

  static constexpr std::uint16_t size  = 64UL;
  static constexpr std::uint16_t magic = 0x5A4DU;

  std::uint16_t e_magic;
  std::uint16_t e_cblp;
  std::uint16_t e_cp;
  std::uint16_t e_crlc;
  std::uint16_t e_cparhdr;
  std::uint16_t e_minalloc;
  std::uint16_t e_maxalloc;
  std::uint16_t e_ss;
  std::uint16_t e_sp;
  std::uint16_t e_csum;
  std::uint16_t e_ip;
  std::uint16_t e_cs;
  std::uint16_t e_lfarlc;
  std::uint16_t e_ovno;
  std::array<uint16_t, 4> e_res;
  std::uint16_t e_oemid;
  std::uint16_t e_oeminfo;
  std::array<std::uint16_t, 10> e_res2;
  std::uint32_t e_lfanew;

  static auto parse(std::span<std::uint8_t> buf, dos_header& header) -> std::error_code {
    if (buf.size() < size) {
      return make_error_code(deep::parser::parse_error::too_small_buffer);
    }

    auto in = zpp::bits::input(buf, zpp::bits::endian::big{});
    in(header);

    if (header.e_magic != magic) {
      return deep::parser::make_error_code(
          deep::parser::parse_error::invalid_magic_number);
    }

    return {};
  }
};

static_assert(sizeof(dos_header) == dos_header::size);
```

**Comment by eyalz800** [comment]
@aymanalqadhi did you check the godbolt link? Are you able to reproduce the error there?

**Comment by aymanalqadhi** [comment]
The code from the godbolt link causes the same compiler error. Could be an issue from Microsoft's end. I'll go ahead and close the issue.

**Comment by eyalz800** [comment]
@aymanalqadhi can you share the godbolt link with the reproduction of the error? On my side it compiled fine. Yea I agree this is a compiler issue but I would still want to understand it and possibly work around or create a short sample to maybe submit a bug to Microsoft.

**Comment by aymanalqadhi** [comment]
The code (with templates) seems to work on GodBolt, but not on Visual Studio. I'll try to repair the installation of Visual Studio, and give you an update.

Here is the link to the code: https://godbolt.org/z/7PTveYYGc

**Comment by eyalz800** [comment]
Check also that you have the latest version of the library

**Comment by aymanalqadhi** [comment]
The same issue persists. I'll wait for the stable Visual Studio 17.3 release then try again. Meanwhile, I will use another library to get my work done (Boost.Serialize perhaps).

**Comment by eyalz800** [comment]
I personally instruct visual studio to compile with clang if that works for you - or you can use my C++14 library https://GitHub.com/eyalz800/serializer

**Comment by aymanalqadhi** [comment]
I make use of C++20's features (such as modules) that cannot be used on clang currently without abandoning automated build systems, and resorting to something like makefiles.
