### ISSUE TITLE
Cannot compile using Visual Studio 2019

### ISSUE THREAD

**Issue by Leopard20** [eyalz800/zpp_bits#80]
It seems like Visual Studio has trouble compiling the file. I get a `fatal error C1004: unexpected end-of-file found` when I include `zpp_bits.h`.
Also Visual Studio's IntelliSense breaks completely for any file that has `#include "zpp_bits.h"` for me.

```cpp
#include "zpp_bits.h"
#include <fstream>
#include <vector>
int main() {
    struct Test {
        using serialize = zpp::bits::members<3>;
        int i = 1, j = 2, k = 3;
    };
    std::vector<Test> tests;
    tests.resize(10);

    std::vector<char> data;
    zpp::bits::out out(data);
    auto result = out(tests);

    std::ofstream save_file("test.txt", std::ios::binary);
    save_file.write(data.data(), data.size());
    save_file.close();

    return 0;
}
```

When I comment out the line `auto result = out(tests);` the error disappears and it builds successfully.

I also tried `#define ZPP_BITS_INLINE_MODE 0` but that wasn't the problem.

**Comment by Leopard20** [comment]
Also I build the project using CMake. Not sure if that matters at all here.
```cmake
cmake_minimum_required(VERSION 3.20)
project(Test LANGUAGES CXX)

add_executable(test src.cpp)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED TRUE FORCE)

set(CMAKE_INCLUDE_CURRENT_DIR TRUE)
target_compile_options(test PUBLIC /O2 /Ob2 /Zi /std:c++20)
```

**Comment by Leopard20** [comment]
I think the problem might be those really long lines. Maybe it will help if you break them down to multiple lines?

**Comment by eyalz800** [comment]
Can you take a look and see if your issue is the same as one of the following or if there is a workaround to it -

https://github.com/eyalz800/zpp_bits/issues/72
https://github.com/eyalz800/zpp_bits/issues/76
https://github.com/eyalz800/zpp_bits/issues/77

I see there is a repeating problem with msvc and the issue is maybe that I only tried msvc via godbolt and for me it worked I may need to download it and test myself

**Comment by Leopard20** [comment]
Issue #72 is not related. Not sure about #77.
It is the same as issue #76. And unfortunately it seems that the workaround in that case was switching to VS2022.

**Comment by Leopard20** [comment]
Also I tried shortening the lines and it helped a bit with the IntelliSense failing but the build still fails. I'll continue to investigate.

**Comment by Leopard20** [comment]
Also one thing I forgot to mention, is that the error seems to point to this line (not sure why):
https://github.com/eyalz800/zpp_bits/blob/27c0dca38fe15e1f650fb1b8ecffb2d470ae7a05/zpp_bits.h#L865

**Comment by eyalz800** [comment]
Can you submit the full error?

**Comment by Leopard20** [comment]
`[build] C:\Projects\zpp_bits\zpp_bits.h(865): fatal error C1004: unexpected end-of-file found`

**Comment by eyalz800** [comment]
Yeah so it’s a duplicate issue, that was resolved by updating to the last visual studio. You can also avoid updating if you instruct visual studio to compile
with clang

**Comment by Leopard20** [comment]
Yeah. Seems like I'm gonna have to switch to VS2022. 
But if you don't mind I'll keep the issue open.

**Comment by eyalz800** [comment]
You can keep it open until you’ve updated and confirm it’s resolved

**Comment by Leopard20** [comment]
Ok so VS2022 does compile the file successfully. But unfortunately the IntelliSense is still broken.
I'll submit a bug to Microsoft.

**Comment by eyalz800** [comment]
Thanks @Leopard20 please update how it goes if you can.

**Comment by RAVER0306** [comment]
Has this problem been solved?

**Comment by RAVER0306** [comment]
> Yes, visual studio 2019 doesn’t support fully C++20 or has some bugs that fail to compile this, use a newer version.

Would you consider supporting C++17?
