### ISSUE TITLE
Reading large amounts of data from a file

### ISSUE THREAD

**Issue by fenghou1st** [eyalz800/zpp_bits#82]
In this case, I cannot read all the data into memory all at once. So maybe I need a stream?
Will this library support something similar?

**Comment by eyalz800** [comment]
It’s better in my opinion to map the file to memory first then pass std::span of the mapped memory. What do you think?

**Comment by fenghou1st** [comment]
This is really a good idea! Thank you!
Fast is the most important thing, I totally agree with your decision.
