### ISSUE TITLE
Can the function signature of explicit serialization not use `auto`?

### ISSUE THREAD

**Issue by fenghou1st** [eyalz800/zpp_bits#94]
```cpp
struct person
{
    constexpr static auto serialize(auto & archive, person & self)
    {
        return archive(self.name, self.age);
    }

    std::string name;
    int age{};
};
```

Will this cause `const person & self` not to be matched?

I want to write this way, because it enables the following member variables to be parsed by the IDE, so that I can quickly find that the member variables are written incorrectly, or have been deleted.

**Comment by eyalz800** [comment]
You need both overloads for const and non const, but there are many ways to work around what you want to do. One of them is to avoid specifying the members - why don’t you use the zpp::bits::members or just rely on aggregate member detection?

**Comment by fenghou1st** [comment]
> You need both overloads for const and non const

Got it, thank you.

> why don’t you use the zpp::bits::members or just rely on aggregate member detection?

Some data are cached data that only exists at runtime. If you don't save them, you can make the saved file smaller and take less time.
Some data are pointers or references to other objects. I think It will cause a lot of trouble if you save them.

**Comment by eyalz800** [comment]
The closest I can think of is to use thr mutable keyword and somehow have the serialization detect that the member is mutable, or introduce some kind of wrapper class to members that need skipping

**Comment by fenghou1st** [comment]
I feel that if we can't implement it gracefully, then we shouldn't implement it.
It's best to do it the C++ way.
