### ISSUE TITLE
can't serialize empty tuple

### ISSUE THREAD

**Issue by zodd-pl** [eyalz800/zpp_bits#96]
First this is a great library.

Issue:
Serializing empty tuple result in compile time error. It would be nice if it didn't like it doesn't for e.g. empty vector.

std::tuple<> t;
auto [m,out] = zpp::bits::data_out();
out(t);

**Comment by eyalz800** [comment]
I see, I didn’t even know you can do that, I’ll plan to add this soon

**Comment by zodd-pl** [comment]
Great. thanks.

My use case is nothing special. Serialization of an empty tuple just pops out in serialization of my class that has member tuple that might be empty depending on template arguments.  And without direct support for empty tuple i have to write an extra if statement  which i would like to avoid:

   constexpr static auto serialize(auto & archive, auto & self) 
    {
        if constexpr ( std::tuple_size<member_tuple_type>{} > 0)
        {
           return archive(self.x,self.member_tuple);
        }
        else
        {
           return archive(self.x);
        }
    }

**Comment by eyalz800** [comment]
Waiting for https://github.com/eyalz800/zpp_bits/pull/97 to see if test pass

**Comment by eyalz800** [comment]
Merged, please check if it resolves the issue and close.

**Comment by zodd-pl** [comment]
It works. That was quick. thanks
